version: "3.0"
services:
  grass_webui:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    container_name: grass_webui
    network_mode: bridge
    ports:
      - "8000:8000"